export default [{
	"label": "福建省",
	"value": "3900",
	"children": [{
		"label": "三明市",
		"value": "3950"
	}, {
		"label": "南平市",
		"value": "4010"
	}, {
		"label": "厦门市",
		"value": "3930"
	}, {
		"label": "宁德市",
		"value": "4030"
	}, {
		"label": "泉州市",
		"value": "3970"
	}, {
		"label": "漳州市",
		"value": "3990"
	}, {
		"label": "福州市",
		"value": "3910"
	}, {
		"label": "莆田市",
		"value": "3940"
	}, {
		"label": "龙岩市",
		"value": "4050"
	}],
}, {
	"label": "西藏自治区",
	"value": "",
	"children": [{
		"label": "山南地区",
		"value": "7740"
	}, {
		"label": "拉萨市",
		"value": "7710"
	}, {
		"label": "日喀则地区",
		"value": "7760"
	}, {
		"label": "昌都地区",
		"value": "7720"
	}, {
		"label": "林芝地区",
		"value": "7830"
	}, {
		"label": "那曲地区",
		"value": "7790"
	}, {
		"label": "阿里地区",
		"value": "7810"
	}],
}, {
	"label": "贵州省",
	"value": "",
	"children": [{
		"label": "六盘水市",
		"value": "7020"
	}, {
		"label": "安顺市",
		"value": "7110"
	}, {
		"label": "毕节市",
		"value": "7090"
	}, {
		"label": "贵阳市",
		"value": "7010"
	}, {
		"label": "遵义市",
		"value": "7030"
	}, {
		"label": "铜仁市",
		"value": "7050"
	}, {
		"label": "黔东南苗族",
		"value": "7130"
	}, {
		"label": "黔南布依族",
		"value": "7150"
	}, {
		"label": "黔西南布依族苗族自治州",
		"value": "7070"
	}],
}, {
	"label": "上海市",
	"value": "2900",
	"children": [{
		"label": "上海市",
		"value": "2900"
	}],
}, {
	"label": "广东省",
	"value": "5800",
	"children": [{
		"label": "东莞市",
		"value": "6020"
	}, {
		"label": "中山市",
		"value": "6030"
	}, {
		"label": "云浮市",
		"value": "6060"
	}, {
		"label": "佛山市",
		"value": "5880"
	}, {
		"label": "广州市",
		"value": "5810"
	}, {
		"label": "惠州市",
		"value": "5950"
	}, {
		"label": "揭阳市",
		"value": "6050"
	}, {
		"label": "梅州市",
		"value": "5960"
	}, {
		"label": "汕头市",
		"value": "5860"
	}, {
		"label": "汕尾市",
		"value": "5970"
	}, {
		"label": "江门市",
		"value": "5890"
	}, {
		"label": "河源市",
		"value": "5980"
	}, {
		"label": "深圳市",
		"value": "5840"
	}, {
		"label": "清远市",
		"value": "6010"
	}, {
		"label": "湛江市",
		"value": "5910"
	}, {
		"label": "潮州市",
		"value": "6040"
	}, {
		"label": "珠海市",
		"value": "5850"
	}, {
		"label": "肇庆市",
		"value": "5930"
	}, {
		"label": "茂名市",
		"value": "5920"
	}, {
		"label": "阳江市",
		"value": "5990"
	}, {
		"label": "韶关市",
		"value": "5820"
	}],
}, {
	"label": "湖北省",
	"value": "3900",
	"children": [{
		"label": "十堰市",
		"value": "5230"
	}, {
		"label": "咸宁市",
		"value": "5360"
	}, {
		"label": "孝感市",
		"value": "5350"
	}, {
		"label": "宜昌市",
		"value": "5250"
	}, {
		"label": "恩施土家族苗族自治州",
		"value": "5410"
	}, {
		"label": "武汉市",
		"value": "5210"
	}, {
		"label": "荆州市",
		"value": "5370"
	}, {
		"label": "荆门市",
		"value": "5320"
	}, {
		"label": "襄阳市",
		"value": "5280"
	}, {
		"label": "鄂州市",
		"value": "5310"
	}, {
		"label": "随州市",
		"value": "5270"
	}, {
		"label": "黄冈市",
		"value": "5330"
	}, {
		"label": "黄石市",
		"value": "5220"
	}],
}, {
	"label": "湖南省",
	"value": "",
	"children": [{
		"label": "娄底市",
		"value": "5620"
	}, {
		"label": "岳阳市",
		"value": "5570"
	}, {
		"label": "常德市",
		"value": "5580"
	}, {
		"label": "张家界市",
		"value": "5590"
	}, {
		"label": "怀化市",
		"value": "5670"
	}, {
		"label": "株洲市",
		"value": "5520"
	}, {
		"label": "永州市",
		"value": "5650"
	}, {
		"label": "湘潭市",
		"value": "5530"
	}, {
		"label": "湘西州",
		"value": "5690"
	}, {
		"label": "益阳市",
		"value": "5610"
	}, {
		"label": "衡阳市",
		"value": "5540"
	}, {
		"label": "邵阳市",
		"value": "5550"
	}, {
		"label": "郴州市",
		"value": "5630"
	}, {
		"label": "长沙市",
		"value": "5510"
	}],
}, {
	"label": "四川省",
	"value": "6500",
	"children": [{
		"label": "乐山市",
		"value": "6650"
	}, {
		"label": "内江市",
		"value": "6630"
	}, {
		"label": "凉山彝族州",
		"value": "6840"
	}, {
		"label": "南充市",
		"value": "6730"
	}, {
		"label": "宜宾市",
		"value": "6710"
	}, {
		"label": "巴中市",
		"value": "6870"
	}, {
		"label": "广元市",
		"value": "6610"
	}, {
		"label": "广安市",
		"value": "6690"
	}, {
		"label": "德阳市",
		"value": "6580"
	}, {
		"label": "成都市",
		"value": "6510"
	}, {
		"label": "攀枝花市",
		"value": "6560"
	}, {
		"label": "泸州市",
		"value": "6570"
	}, {
		"label": "甘孜藏族州",
		"value": "6810"
	}, {
		"label": "眉山市",
		"value": "6670"
	}, {
		"label": "绵阳市",
		"value": "6590"
	}, {
		"label": "自贡市",
		"value": "6550"
	}, {
		"label": "资阳市",
		"value": "6880"
	}, {
		"label": "达州市",
		"value": "6750"
	}, {
		"label": "遂宁市",
		"value": "6620"
	}, {
		"label": "阿坝藏族羌族州",
		"value": "6790"
	}, {
		"label": "雅安市",
		"value": "6770"
	}],
}, {
	"label": "安徽省",
	"value": "3600",
	"children": [{
		"label": "亳州市",
		"value": "3810"
	}, {
		"label": "六安市",
		"value": "3760"
	}, {
		"label": "合肥市",
		"value": "3610"
	}, {
		"label": "安庆市",
		"value": "3680"
	}, {
		"label": "宣城市",
		"value": "3770"
	}, {
		"label": "宿州市",
		"value": "3740"
	}, {
		"label": "池州市",
		"value": "3790"
	}, {
		"label": "淮北市",
		"value": "3660"
	}, {
		"label": "淮南市",
		"value": "3640"
	}, {
		"label": "滁州市",
		"value": "3750"
	}, {
		"label": "芜湖市",
		"value": "3620"
	}, {
		"label": "蚌埠市",
		"value": "3630"
	}, {
		"label": "铜陵市",
		"value": "3670"
	}, {
		"label": "阜阳市",
		"value": "3720"
	}, {
		"label": "马鞍山市",
		"value": "3650"
	}, {
		"label": "黄山市",
		"value": "3710"
	}],
}, {
	"label": "广西省",
	"value": "6100",
	"children": [{
		"label": "广西省",
		"value": "6100"
	}],
}, {
	"label": "江苏省",
	"value": "3000",
	"children": [{
		"label": "南京市",
		"value": "3010"
	}, {
		"label": "南通市",
		"value": "3060"
	}, {
		"label": "宿迁市",
		"value": "3180"
	}, {
		"label": "常州市",
		"value": "3040"
	}, {
		"label": "徐州市",
		"value": "3030"
	}, {
		"label": "扬州市",
		"value": "3120"
	}, {
		"label": "无锡市",
		"value": "3020"
	}, {
		"label": "泰州市",
		"value": "3160"
	}, {
		"label": "淮安市",
		"value": "3080"
	}, {
		"label": "盐城市",
		"value": "3110"
	}, {
		"label": "苏州市",
		"value": "3050"
	}, {
		"label": "连云港市",
		"value": "3070"
	}, {
		"label": "镇江市",
		"value": "3140"
	}],
}, {
	"label": "吉林省",
	"value": "",
	"children": [{
		"label": "吉林市",
		"value": "2420"
	}, {
		"label": "四平市",
		"value": "2430"
	}, {
		"label": "延边朝鲜族",
		"value": "2490"
	}, {
		"label": "松原市",
		"value": "2510"
	}, {
		"label": "白城市",
		"value": "2470"
	}, {
		"label": "白山市",
		"value": "2460"
	}, {
		"label": "辽源市",
		"value": "2440"
	}, {
		"label": "通化市",
		"value": "2450"
	}, {
		"label": "长春市",
		"value": "2410"
	}],
}, {
	"label": "河南省",
	"value": "4900",
	"children": [{
		"label": "三门峡市",
		"value": "5050"
	}, {
		"label": "信阳市",
		"value": "5150"
	}, {
		"label": "南阳市",
		"value": "5130"
	}, {
		"label": "周口市",
		"value": "5080"
	}, {
		"label": "商丘市",
		"value": "5060"
	}, {
		"label": "安阳市",
		"value": "4960"
	}, {
		"label": "平顶山市",
		"value": "4950"
	}, {
		"label": "开封市",
		"value": "4920"
	}, {
		"label": "新乡市",
		"value": "4980"
	}, {
		"label": "洛阳市",
		"value": "4930"
	}, {
		"label": "漯河市",
		"value": "5040"
	}, {
		"label": "濮阳市",
		"value": "5020"
	}, {
		"label": "焦作市",
		"value": "5010"
	}, {
		"label": "许昌市",
		"value": "5030"
	}, {
		"label": "郑州市",
		"value": "4910"
	}, {
		"label": "驻马店市",
		"value": "5110"
	}, {
		"label": "鹤壁市",
		"value": "4970"
	}],
}, {
	"label": "河北省",
	"value": "1200",
	"children": [{
		"label": "保定市",
		"value": "1340"
	}, {
		"label": "唐山市",
		"value": "1240"
	}, {
		"label": "廊坊市",
		"value": "1460"
	}, {
		"label": "张家口市",
		"value": "1380"
	}, {
		"label": "承德市",
		"value": "1410"
	}, {
		"label": "沧州市",
		"value": "1430"
	}, {
		"label": "石家庄市",
		"value": "1210"
	}, {
		"label": "秦皇岛市",
		"value": "1260"
	}, {
		"label": "衡水市",
		"value": "1480"
	}, {
		"label": "邢台市",
		"value": "1310"
	}, {
		"label": "邯郸市",
		"value": "1270"
	}],
}, {
	"label": "海南省",
	"value": "6400",
	"children": [{
		"label": "三亚市",
		"value": "6420"
	}, {
		"label": "三沙市",
		"value": "6440"
	}, {
		"label": "海口市",
		"value": "6410"
	}],
}, {
	"label": "新疆自治区",
	"value": "",
	"children": [{
		"label": "乌鲁木齐市",
		"value": "8810"
	}, {
		"label": "伊犁哈萨克",
		"value": "8980"
	}, {
		"label": "克孜勒苏柯尔克孜自治州",
		"value": "8930"
	}, {
		"label": "克拉玛依市",
		"value": "8820"
	}, {
		"label": "博尔塔拉",
		"value": "8870"
	}, {
		"label": "吐鲁番地区",
		"value": "8830"
	}, {
		"label": "和田地区",
		"value": "8960"
	}, {
		"label": "哈密地区",
		"value": "8840"
	}, {
		"label": "喀什地区",
		"value": "8940"
	}, {
		"label": "塔城地区",
		"value": "9010"
	}, {
		"label": "巴音郭楞",
		"value": "8880"
	}, {
		"label": "昌吉回族",
		"value": "8850"
	}, {
		"label": "阿克苏地区",
		"value": "8910"
	}, {
		"label": "阿勒泰地区",
		"value": "9020"
	}],
}, {
	"label": "江西省",
	"value": "4200",
	"children": [{
		"label": "上饶市",
		"value": "4330"
	}, {
		"label": "九江市",
		"value": "4240"
	}, {
		"label": "南昌市",
		"value": "4210"
	}, {
		"label": "吉安市",
		"value": "4350"
	}, {
		"label": "宜春市",
		"value": "4310"
	}, {
		"label": "抚州市",
		"value": "4370"
	}, {
		"label": "新余市",
		"value": "4260"
	}, {
		"label": "景德镇市",
		"value": "4220"
	}, {
		"label": "萍乡市",
		"value": "4230"
	}, {
		"label": "赣州市",
		"value": "4280"
	}, {
		"label": "鹰潭市",
		"value": "4270"
	}],
}, {
	"label": "重庆市",
	"value": "6900",
	"children": [{
		"label": "重庆市",
		"value": "6900"
	}],
}, {
	"label": "云南省",
	"value": "7300",
	"children": [{
		"label": "临沧市",
		"value": "7580"
	}, {
		"label": "丽江市",
		"value": "7550"
	}, {
		"label": "保山市",
		"value": "7530"
	}, {
		"label": "大理白族州",
		"value": "7510"
	}, {
		"label": "德宏州",
		"value": "7540"
	}, {
		"label": "怒江州",
		"value": "7560"
	}, {
		"label": "文山州",
		"value": "7450"
	}, {
		"label": "昆明市",
		"value": "7310"
	}, {
		"label": "昭通市",
		"value": "7340"
	}, {
		"label": "普洱市",
		"value": "7470"
	}, {
		"label": "曲靖市",
		"value": "7360"
	}, {
		"label": "楚雄彝族州",
		"value": "7380"
	}, {
		"label": "玉溪市",
		"value": "7410"
	}, {
		"label": "红河州",
		"value": "7430"
	}, {
		"label": "西双版纳州",
		"value": "7490"
	}, {
		"label": "迪庆州",
		"value": "7570"
	}],
}, {
	"label": "北京市",
	"value": "1000",
	"children": [{
		"label": "北京市",
		"value": "1000"
	}],
}, {
	"label": "甘肃省",
	"value": "",
	"children": [{
		"label": "临夏回族",
		"value": "8360"
	}, {
		"label": "兰州市",
		"value": "8210"
	}, {
		"label": "嘉峪关市",
		"value": "8220"
	}, {
		"label": "天水市",
		"value": "8250"
	}, {
		"label": "定西市",
		"value": "8290"
	}, {
		"label": "平凉市",
		"value": "8330"
	}, {
		"label": "庆阳市",
		"value": "8340"
	}, {
		"label": "张掖市",
		"value": "8270"
	}, {
		"label": "武威市",
		"value": "8280"
	}, {
		"label": "甘南藏族",
		"value": "8380"
	}, {
		"label": "白银市",
		"value": "8240"
	}, {
		"label": "酒泉市",
		"value": "8260"
	}, {
		"label": "金昌市",
		"value": "8230"
	}, {
		"label": "陇南市",
		"value": "8310"
	}],
}, {
	"label": "山东省",
	"value": "4500",
	"children": [{
		"label": "东营市",
		"value": "4550"
	}, {
		"label": "临沂市",
		"value": "4730"
	}, {
		"label": "威海市",
		"value": "4650"
	}, {
		"label": "德州市",
		"value": "4680"
	}, {
		"label": "日照市",
		"value": "4770"
	}, {
		"label": "枣庄市",
		"value": "4540"
	}, {
		"label": "泰安市",
		"value": "4630"
	}, {
		"label": "济南市",
		"value": "4510"
	}, {
		"label": "济宁市",
		"value": "4610"
	}, {
		"label": "淄博市",
		"value": "4530"
	}, {
		"label": "滨州市",
		"value": "4660"
	}, {
		"label": "潍坊市",
		"value": "4580"
	}, {
		"label": "烟台市",
		"value": "4560"
	}, {
		"label": "聊城市",
		"value": "4710"
	}, {
		"label": "莱芜市",
		"value": "4790"
	}, {
		"label": "菏泽市",
		"value": "4750"
	}, {
		"label": "青岛市",
		"value": "4520"
	}],
}, {
	"label": "陕西省",
	"value": "7900",
	"children": [{
		"label": "咸阳市",
		"value": "7950"
	}, {
		"label": "商洛市",
		"value": "8030"
	}, {
		"label": "安康市",
		"value": "8010"
	}, {
		"label": "宝鸡市",
		"value": "7930"
	}, {
		"label": "延安市",
		"value": "8040"
	}, {
		"label": "榆林市",
		"value": "8060"
	}, {
		"label": "汉中市",
		"value": "7990"
	}, {
		"label": "渭南市",
		"value": "7970"
	}, {
		"label": "西安市",
		"value": "7910"
	}, {
		"label": "铜川市",
		"value": "7920"
	}],
}, {
	"label": "浙江省",
	"value": "3300",
	"children": [{
		"label": "丽水市",
		"value": "3430"
	}, {
		"label": "台州市",
		"value": "3450"
	}, {
		"label": "嘉兴市",
		"value": "3350"
	}, {
		"label": "宁波市",
		"value": "3320"
	}, {
		"label": "杭州市",
		"value": "3310"
	}, {
		"label": "温州市",
		"value": "3330"
	}, {
		"label": "湖州市",
		"value": "3360"
	}, {
		"label": "绍兴市",
		"value": "3370"
	}, {
		"label": "舟山市",
		"value": "3420"
	}, {
		"label": "衢州市",
		"value": "3410"
	}, {
		"label": "金华市",
		"value": "3380"
	}],
}, {
	"label": "内蒙古自治区",
	"value": "",
	"children": [{
		"label": "乌兰察布市",
		"value": "2030"
	}, {
		"label": "乌海市",
		"value": "1930"
	}, {
		"label": "兴安盟",
		"value": "1980"
	}, {
		"label": "包头市",
		"value": "1920"
	}, {
		"label": "呼伦贝尔市",
		"value": "1960"
	}, {
		"label": "呼和浩特市",
		"value": "1910"
	}, {
		"label": "巴彦淖尔市",
		"value": "2070"
	}, {
		"label": "赤峰市",
		"value": "1940"
	}, {
		"label": "通辽市",
		"value": "1990"
	}, {
		"label": "鄂尔多斯市",
		"value": "2050"
	}, {
		"label": "锡林郭勒盟",
		"value": "2010"
	}, {
		"label": "阿拉善盟",
		"value": "2080"
	}],
}, {
	"label": "青海省",
	"value": "",
	"children": [{
		"label": "果洛藏族",
		"value": "8570"
	}, {
		"label": "海东市",
		"value": "8520"
	}, {
		"label": "海北藏族",
		"value": "8540"
	}, {
		"label": "海南藏族",
		"value": "8560"
	}, {
		"label": "海西蒙古族",
		"value": "8590"
	}, {
		"label": "玉树藏族",
		"value": "8580"
	}, {
		"label": "西宁市",
		"value": "8510"
	}, {
		"label": "黄南藏族",
		"value": "8550"
	}],
}, {
	"label": "辽宁省",
	"value": "2200",
	"children": [{
		"label": "丹东市",
		"value": "2260"
	}, {
		"label": "大连市",
		"value": "2220"
	}, {
		"label": "抚顺市",
		"value": "2240"
	}, {
		"label": "朝阳市",
		"value": "2340"
	}, {
		"label": "本溪市",
		"value": "2250"
	}, {
		"label": "沈阳市",
		"value": "2210"
	}, {
		"label": "盘锦市",
		"value": "2320"
	}, {
		"label": "营口市",
		"value": "2280"
	}, {
		"label": "葫芦岛市",
		"value": "2360"
	}, {
		"label": "辽阳市",
		"value": "2310"
	}, {
		"label": "铁岭市",
		"value": "2330"
	}, {
		"label": "锦州市",
		"value": "2270"
	}, {
		"label": "阜新市",
		"value": "2290"
	}, {
		"label": "鞍山市",
		"value": "2230"
	}],
}, {
	"label": "天津市",
	"value": "1100",
	"children": [{
		"label": "天津市",
		"value": "1100"
	}],
}, {
	"label": "黑龙江省",
	"value": "2600",
	"children": [{
		"label": "七台河市",
		"value": "2740"
	}, {
		"label": "伊春市",
		"value": "2710"
	}, {
		"label": "佳木斯市",
		"value": "2720"
	}, {
		"label": "双鸭山市",
		"value": "2680"
	}, {
		"label": "哈尔滨市",
		"value": "2610"
	}, {
		"label": "大兴安岭地区",
		"value": "2790"
	}, {
		"label": "大庆市",
		"value": "2690"
	}, {
		"label": "牡丹江市",
		"value": "2750"
	}, {
		"label": "绥化市",
		"value": "2760"
	}, {
		"label": "鸡西市",
		"value": "2660"
	}, {
		"label": "鹤岗市",
		"value": "2670"
	}, {
		"label": "黑河市",
		"value": "2780"
	}, {
		"label": "齐齐哈尔市",
		"value": "2640"
	}],
}, {
	"label": "广西自治区",
	"value": "",
	"children": [{
		"label": "北海市",
		"value": "6230"
	}, {
		"label": "南宁市",
		"value": "6110"
	}, {
		"label": "崇左市",
		"value": "6360"
	}, {
		"label": "来宾市",
		"value": "6350"
	}, {
		"label": "柳州市",
		"value": "6140"
	}, {
		"label": "桂林市",
		"value": "6170"
	}, {
		"label": "梧州市",
		"value": "6210"
	}, {
		"label": "河池市",
		"value": "6280"
	}, {
		"label": "玉林市",
		"value": "6240"
	}, {
		"label": "百色市",
		"value": "6260"
	}, {
		"label": "贵港市",
		"value": "6330"
	}, {
		"label": "贺州市",
		"value": "6340"
	}, {
		"label": "钦州市",
		"value": "6310"
	}, {
		"label": "防城港市",
		"value": "6320"
	}],
}, {
	"label": "宁夏自治区",
	"value": "8700",
	"children": [{
		"label": "中卫市",
		"value": "8750"
	}, {
		"label": "吴忠市",
		"value": "8730"
	}, {
		"label": "固原市",
		"value": "8740"
	}, {
		"label": "石嘴山市",
		"value": "8720"
	}, {
		"label": "银川市",
		"value": "8710"
	}],
}, {
	"label": "山西省",
	"value": "1600",
	"children": [{
		"label": "临汾市",
		"value": "1770"
	}, {
		"label": "吕梁市",
		"value": "1730"
	}, {
		"label": "大同市",
		"value": "1620"
	}, {
		"label": "太原市",
		"value": "1610"
	}, {
		"label": "忻州市",
		"value": "1710"
	}, {
		"label": "晋中市",
		"value": "1750"
	}, {
		"label": "晋城市",
		"value": "1680"
	}, {
		"label": "朔州市",
		"value": "1690"
	}, {
		"label": "运城市",
		"value": "1810"
	}, {
		"label": "长治市",
		"value": "1660"
	}, {
		"label": "阳泉市",
		"value": "1650"
	}]
}]
